sonar.projectKey=decentralized-identity_didwebvh-java
sonar.organization=decentralized-identity
sonar.projectName=didwebvh-java

sonar.sources=didwebvh-core/src/main/java,didwebvh-signing-local/src/main/java,didwebvh-wizard/src/main/java
sonar.tests=didwebvh-core/src/test/java,didwebvh-signing-local/src/test/java,didwebvh-wizard/src/test/java
sonar.java.binaries=didwebvh-core/target/classes,didwebvh-signing-local/target/classes,didwebvh-wizard/target/classes

sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml
sonar.java.source=11
