package io.github.decentralizedidentity.didwebvh.core.update;

import io.github.decentralizedidentity.didwebvh.core.model.LogEntry;

import java.util.Collections;
import java.util.List;

/**
 * Result of a DID update, migration, or deactivation.
 * Usually contains one new entry; deactivation with active pre-rotation produces two.
 */
public final class UpdateDidResult {

    private final List<LogEntry> newEntries;

    UpdateDidResult(List<LogEntry> newEntries) {
        this.newEntries = Collections.unmodifiableList(newEntries);
    }

    /** All new log entries generated by the operation (in order). */
    public List<LogEntry> getNewEntries() {
        return newEntries;
    }

    /** The last (and usually only) new entry produced by the operation. */
    public LogEntry getLogEntry() {
        return newEntries.get(newEntries.size() - 1);
    }
}
